### PR TITLE
"1 words" fix

### PR DESCRIPTION
**Pull request by fischadi**
all fields are empty, but Content Analysis shows 1 words

### CODE REVIEW

**Comment by TimVevida** [comment]
It seems this PR of yours has two fixes in one: checking for undefined subcontent and trimming the content returned by the plugin.
What is the case where this situation occurs? I could not reproduce it.
And one last hint: when you want to test if the subcontent is not undefined, I would do this at the top of the function addSubContent(), then it also works for nested fields.

**Comment by fischadi** [comment]
You are right. Just trimming the content solved this situation.

**Comment by fischadi** [comment]
Try to create a new page with this field group:
(and then check the content analysis)

`[
    {
        "key": "group_574eec1e90355",
        "title": "Page Header",
        "fields": [
            {
                "key": "field_574eec2da1c32",
                "label": "Title Overwrite",
                "name": "ph_title_overwrite",
                "type": "textarea",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": 50,
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "maxlength": "",
                "rows": 3,
                "new_lines": "br",
                "readonly": 0,
                "disabled": 0
            },
            {
                "key": "field_574eec41a1c33",
                "label": "Background Overwrite",
                "name": "ph_background_overwrite",
                "type": "image",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": 50,
                    "class": "",
                    "id": ""
                },
                "return_format": "array",
                "preview_size": "thumbnail",
                "library": "all",
                "min_width": "",
                "min_height": "",
                "min_size": "",
                "max_width": "",
                "max_height": "",
                "max_size": "",
                "mime_types": ""
            },
            {
                "key": "field_574eec74a1c34",
                "label": "Lead Text",
                "name": "ph_lead_text",
                "type": "text",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "prepend": "",
                "append": "",
                "maxlength": "",
                "readonly": 0,
                "disabled": 0
            },
            {
                "key": "field_574eecd6a1c35",
                "label": "Anchors",
                "name": "ph_anchors",
                "type": "repeater",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "collapsed": "",
                "min": "",
                "max": "",
                "layout": "table",
                "button_label": "Add New",
                "sub_fields": [
                    {
                        "key": "field_574eecf1a1c36",
                        "label": "Button Text",
                        "name": "button_text",
                        "type": "text",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": 50,
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "maxlength": "",
                        "readonly": 0,
                        "disabled": 0
                    },
                    {
                        "key": "field_574eed39a1c38",
                        "label": "Anchor",
                        "name": "anchor",
                        "type": "text",
                        "instructions": "Use css selectors e.g. .content",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": 50,
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "maxlength": "",
                        "readonly": 0,
                        "disabled": 0
                    }
                ]
            }
        ],
        "location": [
            [
                {
                    "param": "post_type",
                    "operator": "==",
                    "value": "page"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": [
            "the_content",
            "featured_image"
        ],
        "active": 1,
        "description": ""
    }
]`

**Comment by solverat** [comment]
does anyone has testet this pr?

**Comment by TimVevida** [comment]
No. But the PR is only partially necessary:

@TimVevida wrote:
> It seems this PR of yours has two fixes in one: checking for undefined subcontent and trimming the content returned by the plugin.

@fischadi wrote:
> You are right. Just trimming the content solved this situation.

But this reply seems to be missing above, or is it modified?

**Comment by fischadi** [comment]
The new version has solved this issues.

**Pull request closed without merging**
